### ISSUE TITLE
Layout issue on mobile

### ISSUE THREAD

**Issue by kierdavis** [srobo/website#10]
This website looks very professional and well-designed. I have noticed a couple of minor layout issues when viewing the site homepage on mobile (Chrome on Android, with a screen resolution of 1280x720) however.

The first issue is that the left hand edge of the navigation links in the top right corner of the page is cut off (see [screenshot][nav-screenshot]). The second is that the footer columns seem to be compressed the left, causing them to overlap (see [screenshot][footer-screenshot]). These issues also are also apparent on other pages of the site.

Other than this, the mobile site works flawlessly for me.

[nav-screenshot]: http://dl.kierdavis.com/Screenshot_20160615-193135.png
[footer-screenshot]: http://dl.kierdavis.com/Screenshot_20160615-193142.png

**Comment by jimmythompson** [comment]
@kierdavis can you just confirm this looks okay now? Cheers. 😄

**Comment by kierdavis** [comment]
Yep, both issues look like they're fixed. Thanks for sorting this :)
