### ISSUE TITLE
Get a TLS certificate for srobo.org

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#141]
We have a certificate for our main studentrobotics.org domain, but it would be great to also have one for our short redirection domain, srobo.org.

As the website is hosted by a Docker container this is a little more interesting than it otherwise might be, though DNS validation or certbot validation within Docker may be options.

**Comment by trickeydan** [comment]
RE docker: Traefik will do this for you. https://docs.traefik.io/configuration/acme/

**Comment by PeterJCLaw** [comment]
Note: https://github.com/srobo/infrastructure/issues/4 currently impacts this too.

**Comment by sedders123** [comment]
See https://github.com/srobo/infrastructure/issues/4
