### ISSUE TITLE
Renew TLS certificates

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#152]
The TLS cert for `*.studentrobotics.org` expires in a couple of months (1st August 2019). We'll need a new one before then, ideally several weeks in advance.

I don't know who has the credentials to do this, I'm guessing either @richardbarlow or @jimmythompson does though.

While doing this we should also consider:
- whether we want to continue using paid certs (rather than, say, Let's Encrypt)
- whether we want to continue having a wildcard cert (or instead have separate certs for subdomains)
- getting a cert for the `srobo.org` domain (as suggested in https://github.com/srobo/website/issues/141)

**Comment by trickeydan** [comment]
Reasons why wildcard certs are a terrible idea:

- Leaking the key: https://twitter.com/Scott_Helme/status/931157779162820608
- If the certificate is revoked, then all servers which use that certificate will need to be updated to use the new certificate. 
- The certificate will expire at some point, which means it will need to be replaced with a new certificate. Much like the point of the revoked certificate above, the same challenges could be face with an expired certificate. If the certificate is not renewed in time, one could face a significant outage.

https://blog.sean-wright.com/wildcard-certs-not-quite-the-star/

**Comment by trickeydan** [comment]
I believe this has now been resolved by the Digitalocean migration?

**Comment by PeterJCLaw** [comment]
Yes. The main website [infrastructure](https://github.com/srobo/infrastructure) is auto-updating and our other puppeted things have also moved to letsencrypt.
