### ISSUE TITLE
Better 404 and 50x pages

### ISSUE THREAD

**Issue by jimmythompson** [srobo/website#16]
Recently, I hastily added some error pages, which just say "Whoops!" These could be better.

They're currently sat in missing.html (404) and error.html (50x).

**Comment by jimmythompson** [comment]
I styled them up, so they don't look so terrible.

![missing](https://cloud.githubusercontent.com/assets/653864/18106996/e9f3975e-6efd-11e6-9e5b-74699e632a81.png)
https://srobo.github.io/website/missing/

![error](https://cloud.githubusercontent.com/assets/653864/18106997/eda24986-6efd-11e6-85c6-05cc88bbbbb8.png)
https://srobo.github.io/website/error/

**Comment by PeterJCLaw** [comment]
Do we really need people to report the issue? Surely we can just look in
the HTTP logs? (or have a monitoring thingy which does that and warns us
about any repeat items)
