### ISSUE TITLE
Serve the website using GitHub Pages?

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/website#162]
This issue serves more as a discussion point as to whether this is a good idea or not. It's been discussed a couple times, but never went anywhere.

## Currently

The website is served out of a docker container using NGINX's default static file server. This same NGINX configuration also handles reverse proxying for all our other applications ([NGINX config](https://github.com/srobo/website/blob/master/_env/nginx.conf)), whether they be on [`patience`](https://github.com/srobo/server-puppet/tree/patience), or other hosts.

## The problem

Currently, to deploy the website requires rebuilding and re-deploying the entire docker container deployment. Because we don't version our containers, this requires forcing Kubernetes to pull the new container image.

## The solution

As the title suggests, we move the hosting of the website to GitHub Pages, and convert the existing configuration to a simple reverse proxy. Because we use custom plugins, we'll need to build the website on CI, and push it to the `gh-pages` branch manually, rather than rely on GitHub building it for us.

### The benefits

- Auto deployment (we could do this anyway, but it's much simpler)
- Simpler deployment process
- Decouple the Docker configuration and the website (maybe move the docker configuration into [`infrastructure`](https://github.com/srobo/infrastructure/)?)
- GitHub handles the static server configuration rather than us
- Barrier to entry for pushing a change live is much lower

### The drawbacks

- It takes time
- What we have does work, pretty well!
- It's a dependency on a 3rd party
- It's another moving part to consider for the website itself.
- Is there a reason it's setup as it is (historical or otherwise) i'm not considering?
- More people would have access to push changes live (well, by default, we could restrict this if necessary)

@jimmythompson / @PeterJCLaw especially interested in your thoughts.

**Comment by jimmythompson** [comment]
This has been my goal for a while now. Would love a PR. Otherwise I’ll work
on it when I have time.

**Comment by RealOrangeOne** [comment]
Glad to see you share my thoughts. I'll try and throw a PR together in the short term and see how far I can get!

**Comment by PeterJCLaw** [comment]
👍 here.

I suggest for the immediate term that we keep the nginx in this repo _as well_ and have a single CI build which does both. That keeps the moving parts to a minimum. We can then separately extract the `_env` folder (probably to its own repo, though https://github.com/srobo/infrastructure/ might also fit), preserving the history.
(Alternatively we could do the `_env` extraction _first_ and have it proxy to "itself" for a bit. That actually might be easier from a minimal-moving-parts perspective, though relies on someone with history-extraction knowledge).

**Comment by PeterJCLaw** [comment]
Oooh, I was going to mention: I suggest switching the `brand` inclusion to being a submodule -- this is what the other website components (i.e: docs, style, competition-website) do and it avoids the build-time stuff around pulling in a single `npm` package. It also means the update process is the same for all the components.

**Comment by PeterJCLaw** [comment]
> Oooh, I was going to mention: I suggest switching the `brand` inclusion to being a submodule -- this is what the other website components (i.e: docs, style, competition-website) do and it avoids the build-time stuff around pulling in a single `npm` package. It also means the update process is the same for all the components.

I've done this in #168.

> We can then separately extract the `_env` folder (probably to its own repo, though https://github.com/srobo/infrastructure/ might also fit), preserving the history.
> (Alternatively we could do the `_env` extraction _first_ and have it proxy to "itself" for a bit. That actually might be easier from a minimal-moving-parts perspective, though relies on someone with history-extraction knowledge).

Per @jimmythompson's suggestion of a `reverse-proxy` repo (https://github.com/srobo/website/pull/165#issuecomment-537406845) I've done this: https://github.com/PeterJCLaw/sr-reverse-proxy. It would be great to get some eyes on that and then I'll transfer it into the org and we can set up the Circle CI config (I don't think I have the docker credentials to do that where it is now).

**Comment by PeterJCLaw** [comment]
> Per @jimmythompson's suggestion of a `reverse-proxy` repo ([#165 (comment)](https://github.com/srobo/website/pull/165#issuecomment-537406845)) I've done this: https://github.com/PeterJCLaw/sr-reverse-proxy. It would be great to get some eyes on that and then I'll transfer it into the org and we can set up the Circle CI config (I don't think I have the docker credentials to do that where it is now).

This happened: https://github.com/srobo/reverse-proxy

**Comment by RealOrangeOne** [comment]
I've enabled the site build using GitHub Pages based on the `master` branch, and looks to be working great! https://srobo.github.io/website/

Next steps are to point the container to use it, rather than its own files. That'll likely be done via https://github.com/srobo/reverse-proxy, though.
