### ISSUE TITLE
Change volunteer sign up page if using Google Groups

### ISSUE THREAD

**Issue by antoinepetty** [srobo/website#163]
![image](https://user-images.githubusercontent.com/36314396/65795714-d0584080-e162-11e9-92ee-0280e46931d5.png)
Currently references MailChip's privacy policy

**Comment by RealOrangeOne** [comment]
We're currently still using Mailchimp, and still will do for a while. 

But when we change to Google Group, we'll definitely want to change this!

**Comment by antoinepetty** [comment]
I'll close this since it's not really relevant!
