### ISSUE TITLE
nginx needs to forward some more 'critical' things

### ISSUE THREAD

**Issue by rspanton** [srobo/website#17]
There are a few things that the nginx config doesn't currently pass through to saffron:
- gerrit-ssh
- userman

There are some other things, but they are less urgent for the competition launch.

**Comment by PeterJCLaw** [comment]
The puppet configs surely get this right...?

**Comment by rspanton** [comment]
This is referring to [this](https://github.com/srobo/website/blob/gh-pages/_env/nginx.conf) nginx config.

**Comment by jimmythompson** [comment]
I think userman is now [done](https://studentrobotics.org/userman).

Forwarding SSH through nginx seems awkward, will have to take a look at this.

**Comment by jimmythompson** [comment]
The future of hosted Git/Gerrit is in question, so I'm closing this.
