### ISSUE TITLE
nginx should also forward other things

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#18]
#17 records critical things, but there are others which should be added too:
* cgit
* comp-api

And possibly others I can't think of right now (please add them to this ticket).

**Comment by jimmythompson** [comment]
Where is the comp api on Saffron?

**Comment by PeterJCLaw** [comment]
https://saffron.studentrobotics.org/comp-api/

**Comment by PeterJCLaw** [comment]
The items specified here are done; others can now have their own tickets.
