### ISSUE TITLE
Rendering issues in IE11

### ISSUE THREAD

**Issue by thomasleese** [srobo/website#19]
There are a few rendering issues in IE11, mostly in the header area so nothing which impacts access to information, it just looks a bit odd.

![capture](https://cloud.githubusercontent.com/assets/510498/18264193/c810c14e-7406-11e6-9e57-ba93abce14ff.PNG)

**Comment by jimmythompson** [comment]
I think I fixed the black background problem, still getting round to the logo and the escaping header.

**Comment by PeterJCLaw** [comment]
We should decide which versions of IE we want to support and document that somewhere. For reference, I've tried to keep support for at least IE 9 in the IDE (and occasionally check that IE 8 isn't too badly broken).

It's also worth knowing that [we have](https://groups.google.com/d/topic/srobo-devel/WDOQGA1lRD0/discussion) a [browserstack](https://www.browserstack.com) account.

**Comment by PeterJCLaw** [comment]
For fun I've just rendered the homepage using said account. The results are here: https://www.browserstack.com/screenshots/8b7cf042b1cffd1867f539603779a61050aee54b. There are clearly some serious issues with IE 8/9, though 10 & 11 are a little better.

**Comment by PeterJCLaw** [comment]
I dug into this the other day and it turns out that it's due to IE _still_ not supporting SVG properly: http://caniuse.com/#search=svg

I _think_ we can fix this by changing the apparent size of the SVG to match the box it gets rendered within, though it would be equally valid to just drop a PNG image in there instead.

**Comment by PeterJCLaw** [comment]
Closing as IE11 is now old enough that I don't think we should care. Also we replaced the SVGs with PNGs, which covers most of it.
