### ISSUE TITLE
Fix security headers

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#24]
We should be emitting at least `Strict-Transport-Security` and probably also `X-Frame-Options`, both of which were active previously.

I'm guessing this is just an oversight in the nginx config?

For reference, the values we used previously were:

```
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
```

**Comment by jimmythompson** [comment]
Just ran this:

https://securityheaders.io/?q=https%3A%2F%2Fstudentrobotics.org%2Fide&hide=on&followRedirects=on

Looking at the results, it's recommending we add the following headers:

* X-Content-Type-Options
* X-XSS-Protection
* Public-Key-Pins

I'm not sure about pinning the public key, but the first two seem like decent suggestions.

**Comment by PeterJCLaw** [comment]
These additional headers have very limited value; there has already been a discussion on the srobo-devel mailing list about them (see thread "[securityheaders.io](https://groups.google.com/d/topic/srobo-devel/jKUSG6D40nI/discussion)"; you might also want to read "[HSTS preload and subdomains](https://groups.google.com/d/topic/srobo-devel/tD2RdI4VJng/discussion)" too) and we concluded that we didn't really need them.

Certainly the sentiment was that pinning the public key was more likely to cause us issues than aid security.

The only other header we thought was useful was `Content-Security-Protection`, which has been added to some of our services individually (I've actually just fixed this in the IDE).

**Comment by PeterJCLaw** [comment]
Incidentally, why did you run that on the IDE rather than the homepage?

**Comment by jimmythompson** [comment]
> These additional headers have very limited value; there has already been a discussion on the srobo-devel mailing list about them (see thread "securityheaders.io"; you might also want to read "HSTS preload and subdomains" too) and we concluded that we didn't really need them.

Fair enough. 😄 

> Incidentally, why did you run that on the IDE rather than the website homepage?

The IDE was the first thing I could think of that's on Saffron, so has the double headers. It does produce a warning in the securityheaders.io report.

**Comment by PeterJCLaw** [comment]
I can't remember where I reported this previously, but it looks like the fix to this has resulted in things which are being served from saffron having the STS headers duplicated. I think we probably want to have nginx _set_ these headers rather than _add_ them, if that's possible?

**Comment by PeterJCLaw** [comment]
A quick investigation suggests that we'll need to use [`proxy_hide_header`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_hide_header) to hide the ones we don't want (via https://stackoverflow.com/questions/31017524/how-to-add-headers-in-nginx-only-sometimes).

**Comment by PeterJCLaw** [comment]
https://cipherli.st/ seems like a useful reference for security configuration of nginx, which might be useful to us for securing our configuration.

**Comment by sedders123** [comment]
@srobo/infrastructure-team Is this something we want to look at? (https://securityheaders.com/?q=https%3A%2F%2Fstudentrobotics.org&hide=on&followRedirects=on)

**Comment by PeterJCLaw** [comment]
> I can't remember where I reported this previously, but it looks like the fix to this has resulted in things which are being served from saffron having the STS headers duplicated. I think we probably want to have nginx _set_ these headers rather than _add_ them, if that's possible?

saffron no longer exists and from what I can see we no longer have any duplication of headers, so this is solved.

**Comment by PeterJCLaw** [comment]
https://securityheaders.com/ suggests:
- `Content-Security-Policy`: this likely isn't much use for us now that we're all static. The main thing it guards against is XSS type issues, which static sites don't have (kinda by definition). I don't think this is worth adding at this point.
- `X-Content-Type-Options`: again this looks like it's not very useful for a static site. There's likely nothing wrong with us setting it (hopefully nginx's sniffing is good enough), but there's also no real benefit.
- `Referrer-Policy`: as far as I can tell this is a _privacy_ thing not a _security_ thing. Again as we're a fully public static site this doesn't seem worthwhile for us to add. (I don't know how users would configure this in their browser, but that seems like a sensible place for this to be configured in general. With maybe a few exceptions, the level of privacy needed for referrers is going to vary by person and I don't think we should be at all restrictive here)

Since the original things this issue was created for are solved I'm going to close this.
