### ISSUE TITLE
Old website still accessible

### ISSUE THREAD

**Issue by rgilton** [srobo/website#26]
If one points one's browser at http://git.studentrobotics.org, one currently gets the old SR website.  This is not ideal, as I imagine things like Google will end up there at some point.

A simple solution to this problem is to replace index.php in the old srweb with something that just immediately redirects the user to https://www.studentrobotics.org/.

**Comment by rspanton** [comment]
I've made a patch for srweb that will do this.  It's in [https://www.studentrobotics.org/gerrit/#/c/2761/](gerrit) currently.  Jimmy, if you're happy for that patch to go through I will make it live.

**Comment by PeterJCLaw** [comment]
Surely a better fix would be to stop saffron serving srweb at all? That avoids confusing people who visit https://saffron.studentrobotics.org/ explicitly.

**Comment by PeterJCLaw** [comment]
`saffron` is gone. https://patience.studentrobotics.org/ exists, however it doesn't host `srweb` anywhere. This is therefore sorted.
