### ISSUE TITLE
Naming and routing for more generic blog posts

### ISSUE THREAD

**Issue by sedders123** [srobo/website#284]
Going forward we want to be posting more blog posts to help attract new sponsors, volunteers and teams. These could be interviews with ex-competitors, more general posts around STEM education, and maybe some technical posts about the ways we've solved any interesting challenges. The actual types of content are not confirmed yet but just wanted to make it clear it won't be just articles about the competition cycle on our website going forwards.

At the moment our posts are hosted under the `/news/` route on the website and we refer to them as 'News' on the website itself. Is it fine to post these more general articles under the name and route of 'news' or should we change the route for all posts to be `/blog/` (or maybe `/articles/`) and refer to them as Articles or Blog Posts? There is way with Jekyll we can redirect the old `/news/` routes to prevent breaking any links in the wild.

I guess another potential option would be to have both a `/news/` and a `/blog/` and competition news goes on news and other stuff goes on blog, though feels like displaying this on the website could be a little confusing to an end user.

At the moment I think I'm leaning towards the rename everything to Blog Posts and use the `/blog/` route (with redirects) but keen to hear what others think!

**Comment by RealOrangeOne** [comment]
+1 for more blog-style content!

I don't feel especially strongly either way, but I think regardless of which approach is chosen, we still need a way of people seeing just the news content or just the blog content, as it makes scanning and reading much easier, as well as obviously a unified feed. Exactly how Jekyll will implement that I don't know.

**Comment by sedders123** [comment]
Do we really need a way for people to see just news or just blogs? First Robotics seem to have [one feed](https://www.firstuk.org/stories/) (named stories) used for both news and articles. Raspbery Pi Foundation just has [a blog](https://www.raspberrypi.org/blog/) they use for both. 

It looks like its non trivial to have separate but also unified views with GitHub Pages Jekyll so we'd likely have to switch to building Jekyll ourselves in CI and then deploying built files to GitHub Pages which feels like quite the change and some effort. Happy to be convinced otherwise but right now I'm not seeing the need for seperation
