### ISSUE TITLE
Urls without trailing slashes redirect via insecure HTTP

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#290]
For example the homepage at https://studentrobotics.org contains a link to `/volunteer` which, as you'd expect, goes to https://studentrobotics.org/volunteer. However _that_ page is then served as a redirect to http://studentrobotics.org/volunteer/ (adding the trailing slash, but removing the TLS).

In my browser config (Firefox, with HTTPS-Only Mode enabled) this means I get a warning when clicking the link.

I had thought we'd seen and fixed this in the past, but I can't recall the exact details nor the fix.

```
$ curl -I https://studentrobotics.org/sponsor
HTTP/1.1 301 Moved Permanently
server: nginx/1.21.1
location: http://studentrobotics.org/sponsor/
```

**Comment by PeterJCLaw** [comment]
Think I found where I was thinking we'd seen this before: https://github.com/srobo/website/issues/122#issuecomment-457387477

**Comment by PeterJCLaw** [comment]
Not sure what changed (since the links haven't) but this has stopped showing issues for me in Firefox :thinking:

**Comment by sedders123** [comment]
Think this has been resolved with the move to `monty`

```
$ curl -I https://studentrobotics.org/sponsor
HTTP/1.1 301 Moved Permanently
Server: nginx/1.18.0 (Ubuntu)
Date: Thu, 03 Mar 2022 20:34:37 GMT
Content-Type: text/html
Location: https://studentrobotics.org/sponsor/
Connection: keep-alive
permissions-policy: interest-cohort=()
x-origin-cache: HIT
Access-Control-Allow-Origin: *
expires: Thu, 03 Mar 2022 20:44:37 GMT
Cache-Control: max-age=600
x-proxy-cache: MISS
X-GitHub-Request-Id: 2E30:E6FB:266CEF0:27BB0D7:6221265D
Accept-Ranges: bytes
Via: 1.1 varnish
Age: 0
X-Served-By: cache-lon4269-LON
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1646339677.448991,VS0,VE102
Vary: Accept-Encoding
X-Fastly-Request-ID: e8885eaae1d9881ffde305832b6572af5abc226e
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
```
