### ISSUE TITLE
Drop underlines on links

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#31]
This was something we very successfully removed in srweb, but appear to have crept back. Underlining is a historic left-over from when it was hard to make things stand out in other ways and is rather ugly.

**Comment by jimmythompson** [comment]
I think the links right now look too intense, and distract from the content. However, I think this is because of the orange, and I think they should still be underlined.

To quote [GDS](https://designpatterns.hackpad.com/Links-CgBO9L4bF4a):

> In most cases, 'make links look like links' means:
* make them blue
* underline them
* make them describe the thing they link to

**Comment by PeterJCLaw** [comment]
While I agree that GDS have a great site, I don't think we need to follow their guide completely -- extracting the essence should be enough.

#### Blues
Their site is heavily themed around a number of blues (and black), so them using another couple of blues that for links works well. I can also see why they've said what they say, but I'd be happy with "make them a distinct colour" or something as the guideline.

Unless we're going to introduce another blue into our site I suspect that blue won't work for us.

#### Underlines
Note that their underlines are moved down to be at the tip of low-hanging letters such as 'y', where ours strike through the hanging part.

The places I most notice this are:
- the docs menu on the left hand side
- the titles which link to themselves (which are also in ALL CAPS)

In both cases the underlines contribute to making it feel like a giant block of orange, rather than something with text in.

#### Describe the target
I wholeheartedly agree with this one, and have been pushing in this direction for many years.

**Comment by sedders123** [comment]
After chatting about this in a marketing team meeting we think that we should leave underlines on our links primarily from an accessibility perspective https://webaim.org/techniques/hypertext/link_text#underlining
