### ISSUE TITLE
Remove IDE from teams dashboard

### ISSUE THREAD

**Issue by antoinepetty** [srobo/website#331]

**Comment by PeterJCLaw** [comment]
@antoinepetty do you have any thoughts on what we should put instead?

**Comment by antoinepetty** [comment]
I'm starting to think that page is just there to be a link to the docs

**Comment by PeterJCLaw** [comment]
Yeah, the teams dashboard doesn't feel like it's really achieving a lot at the moment. The events bit is kinda useful though.

I suggest we worry about reworking the page as a whole separately though.

**Comment by antoinepetty** [comment]
If you want a quick solution - I would either remove it and spread the other two, or link it to the ide-replacement part of the docs (which is what we did for forum->discord in that section)

**Comment by PeterJCLaw** [comment]
Yeah, we (on the Doing call) wondered about linking to the code editors part of the docs, but thought that two links to the docs wasn't the best.
