### ISSUE TITLE
Links from events to more information

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#34]
At the moment the [events page](https://studentrobotics.org/events/) just shows the bare minimum of information about an event. While that is a useful reference, anyone actually coming to an event is going to want considerably more information.

In the past we've had a page dedicated to a given event, and the were linked from the old "key dates" page. I think we should aim for a similar system in the new website, albeit with a bit more structure to how we store the data.

With that in mind, I think we want a setup where:
- events are listed centrally, dynamically
- the information (both short- and long-form) for an event is all stored in a single place
- where possible the information about an event is recorded exactly once

Currently despite the minimal information available we already have duplication of the date of the event (in the file name and within the front matter). This is liable to cause copy-paste errors among other things, so we should sort it sooner rather than later.

**Comment by PeterJCLaw** [comment]
cc @jimmythompson for design thoughts and @Adimote as this may affect the Kickstart pages

**Comment by jimmythompson** [comment]
I had a quick stab at this for kickstart:

![screen shot 2016-10-07 at 08 33 20](https://cloud.githubusercontent.com/assets/653864/19182039/bc34c65c-8c68-11e6-8e2c-7133abbb3c98.png)

https://studentrobotics.org/events/sr2017/southampton-kickstart/
https://studentrobotics.org/events/sr2017/bristol-kickstart/
https://studentrobotics.org/events/sr2017/oxford-kickstart/

Each event has a content section which can contain any information we can't sensibly extract into metadata.

I think there's plenty of things we can flesh out in the metadata, (e.g. links to volunteer forms, and coordinates, etc.) which can power more calls to action and more dynamic elements of the page.

**Comment by richardbarlow** [comment]
Hey Jimmy,

Those event pages look awesome. I see that you currently have a mailto link to teams@ when referring to the local team coordinator. That email address goes to the team coordinator, not any specific local team coordinator. We generally don't want teams contacting the team coordinator directly (other than in exceptional circumstances) as that puts an unmanageable load on a single person. The idea is that all communication with a given team is handled by their local team coordinator, who can pass information on if necessary. Obviously this makes things slightly more complicated for teams though. I think in the future it would be good to have a page hosted somewhere (it doesn't belong in the pr website) that lists teams and who their local team coordinator is. That page can then be linked to in situations like this.

In the mean time you could maybe remove the link around the existing text and add a footnote or some parenthesised text saying "[mailto]contact the team coordinator[mailto] if you don't know who this is"

**Comment by jimmythompson** [comment]
I've removed the links entirely for now, in an attempt to save Fiona's inbox!

**Comment by PeterJCLaw** [comment]
Meta: Do we have specific email addresses for each of the LTCs? If not I think we should, even if they're only of the form teams+$LOCATION@sr (actually I think doing it that way is probably better than separate addresses as the LTCs and the TC can then trivially collaborate if needed)

@jimmythompson the pages are great, though unfortunately there's a rendering issue for me (Firefox) -- the lists (of directions info) have paragraph elements inside the `<li>`s, which means that they get forced onto their own lines (which looks rather odd):

![render-bug](https://cloud.githubusercontent.com/assets/336212/19206465/2186fe12-8ce1-11e6-8b37-c3670d918e69.png)

What I can't work out is why the `<li>` elements get `<p>` elements inside them here when the same doesn't happen elsewhere on the site.

**Comment by PeterJCLaw** [comment]
The render bug turns out to be due to the extra lines between the list elements in the source. Fix: don't do that.

**Comment by PeterJCLaw** [comment]
@jimmythompson I think we can call this fixed?

**Comment by jimmythompson** [comment]
Yep. 👍
