### ISSUE TITLE
(Idea) Some volunteer job descriptions on the volunteer page

### ISSUE THREAD

**Issue by antoinepetty** [srobo/website#359]
Credit to @sedders123 

We could have some brief headings and descriptions of desired volunteer positions
e.g. "we're looking for a competition team member, expected to attend meetings roughly once a week (though missing a few is fine!), help take on tasks around venue booking, sourcing tables chairs etc"

It's important to keep the wording of the page clear that we're accepting all kinds of volunteers, not just the examples listed

**Comment by antoinepetty** [comment]
Maybe also a description of the teams

**Comment by sedders123** [comment]
With our current onboarding process we can't really see a way of doing this. Think we could cover some of this with the changes for #13 instead so will close for now
