### ISSUE TITLE
Typo at srobo.org/compete/

### ISSUE THREAD

**Issue by steppers** [srobo/website#38]
FAQ at the bottom of the page reads 'How much does time does it take?' as opposed to 'How much time does it take?'

**Comment by Adimote** [comment]
I've submitted a PR to fix this, #39

**Comment by PeterJCLaw** [comment]
Meta: @Adimote If you include in either the commits on a PR or the PR text itself which issue it fixes (typically in the form "Fixes #38" then github will:
- link back from the issue to the PR automagically
- (I think) close the issue when the PR merges

**Comment by Adimote** [comment]
@PeterJCLaw Ah, that's useful to know, thanks!

**Comment by jimmythompson** [comment]
Fixed in #39.
