### ISSUE TITLE
Short name DNS entries not redirecting properly

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#44]
The common ones are:
- http://trac.srobo.org/
- http://ide.srobo.org/

Oddly, http://gerrit.srobo.org/ does appear to redirect properly.

In each case http://THING.srobo.org/PAGE should redirect to https://studentrobotics.org/THING/PAGE. In both cases they fail to add `/THING` to the url, resulting in an error page.

I'm fairly sure this is a DNS issue, rather than something in this repo, but don't have a better place to report it.
cc @rspanton

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/infrastructure/issues/4 currently impacts this.

**Comment by sedders123** [comment]
@PeterJCLaw Is this still worth having open? We no longer use Trac or the IDE

**Comment by PeterJCLaw** [comment]
Indeed. I'm actually now of the opinion that we should move to unifying around urls with proxying rather than subdomains too, so if anything I think we should consider this as "won't fix".
