### ISSUE TITLE
no padding between pictures and text

### ISSUE THREAD

**Issue by Adimote** [srobo/website#45]
There's some ugly lack of padding between the images and the text on the docs
example:
![chrome_2016-10-12_17-55-07](https://cloud.githubusercontent.com/assets/2551763/19319519/13e035ea-90a5-11e6-8108-7901263a89a6.png)

between principal and the image

**Comment by PeterJCLaw** [comment]
@Adimote is this just a docs issue, or something more general? If it's just docs, I think I've fixed it in https://github.com/srobo/docs/pull/46.

**Comment by Adimote** [comment]
Belatedly marking as fixed, was fixed in https://github.com/srobo/docs/pull/46
