### ISSUE TITLE
Ensure the "Next Event" is always in the future

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#488]
As the site is statically built, it is possible for the Next Event to pass without the website being regenerated.
This isn't ideal as it both hides the actual next event and makes the site look broken.

One solution would be to have the site rebuild itself on a cron, perhaps after moving to using GitHub Actions to explicitly build the site rather than using the implicit GitHub Pages approach.

**Comment by sedders123** [comment]
The site is now rebuilt daily (in #536) so the 'Next Event' should now move to the next day without explicit intervention from us.
