### ISSUE TITLE
Full stack local development instructions

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#50]
There are currently no details on how to actually test the nginx config, meaning that changes to it are being made blind.

On #35 Jimmy mentioned the use of docker to do this (copied below), but it is non-obvious how complete this is, nor what other things are needed to have a complete local copy of the SR web presence.

The purpose of this ticket is to capture this need and gather the information needed to get started, with the aim of eventually adding some docs to the repo.

Jimmy wrote:

> To test the reverse proxy, you first need to generate an SSL private key (named `key.pem`) and a certificate (named `cert.pem`), and place them in a folder, so they can be mounted into the container.
> 
> If you then run these commands, you should have a working copy of the website on port 5679. 
> 
> ``` shell
> rake build
> docker run -p 5678:443 -p 5679:443 -v (your secret folder):/etc/secrets --name srobo srobo/website
> ```
> 
> Making this process easier would be much appreciated.

Questions to answer:
- what is `docker` and where do I get it from (is there any setup needed for it beyond installing it?)
- it looks like it's setting up two ports which both forward to the same target -- is that intentional?
- how does one generate the requisite SSL keys? (Can/should we use the keys from the [dummy-secrets](https://git.studentrobotics.org/cgit/server/dummy-secrets.git) repo)
- what is secret about the secret folder (and what goes in it? Is it just the SSL keys?)

**Comment by jimmythompson** [comment]
> how does one generate the requisite SSL keys? (Can/should we use the keys from the dummy-secrets repo)

It'd be nice if this was automated as part of `rake build`, any self-signed cert will do. We could define the location of the secrets folder and ignore it in git.

> it looks like it's setting up two ports which both forward to the same target -- is that intentional?

No, my bad. 😅

One is forwarding port 80, one for 443.

> what is secret about the secret folder (and what goes in it? Is it just the SSL keys?)

For now, yes.

**Comment by PeterJCLaw** [comment]
Ok, so I'm going to assume that we're talking about [this Docker](https://www.docker.com/) (which Ubuntu's repo calls `docker.io`) here. I've installed that.
I've then also done the hack where you need to add your user to a group `sudo usermod -aG docker $USER` so you can actually use the thing, complete with manadatory reboot (seriously, WTF it's 2016 -- reboots on install haven't been a thing for decades).

I've then created a certificate using the command from https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl: `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem` which appears to have created some files.

However when running the command above (with minor changes so the ports make sense) it errors:
``` shell
$ docker run -p 5080:80 -p 5443:443 -v secrets:/etc/secrets --name srobo srobo/website
2016/10/22 20:40:30 [emerg] 1#1: BIO_new_file("/etc/secrets/cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/secrets/cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] BIO_new_file("/etc/secrets/cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/secrets/cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

Other things I've discovered:
* `docker version` can be used to validate that the 'server' part of docker can be reached
* `docker start` and `docker stop` look like they should do useful things, but don't (not sure if that's related to the above error though)
* `docker ps -a` lists all the available docker things (without the `-a` it apparently only shows the running ones)
* I currently need to `docker rm srobo` in order to be able to `docker run ...` again, otherwise I get the unhelpful message that "docker: Error response from daemon: Conflict. The name "/srobo" is already in use by container <big-hex-number>. You have to remove (or rename) that container to be able to reuse that name."
* Docker has a **very poor** security standpoint. https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface roughly explains all the ways in which it opens the host machine to bad things and then essentially states "we have some ideas on how to fix this, but haven't got around to it yet". This seems like a _terrible_ place to be for something which is increasingly being used for critical infrastructure web hosting. I suppose it also explains why no-one seems to actually want to run docker on their own machines, instead farming that out to cloud providers.

So far, this is proving to be about as painful as it was to get puppet going, possibly more so given that that didn't need a reboot (comparing to before we wrappered puppet in a Vagrant).

**Comment by PeterJCLaw** [comment]
One upshot of the security insanity that Docker is means that we should probably make it easy to run Docker _inside_ a VM so that we're not forcing our volunteers to expose their own machines.

**Comment by PeterJCLaw** [comment]
@jimmythompson Thanks for adding those patches. They appear to make this mostly work, though there are some issues:
- the certificate is regenerated on every run, meaning that users need to add a new certificate exception every time they run the container locally. I've fixed this in #54.
- the container redirects to the real website if you try to visit on port 80. I can see why this happens, but this is going to lead to a lot of wasted debugging time and should be fixed ASAP.
- the container tries to bind to port 80 and 443 on the host. This is bad since developers are likely to already be using those ports (I have apache running on port 80 for example).
- the container tries to bind to the global `0.0.0.0` address (on the host side) rather than the more restrictive `127.0.0.1`. This could lead to security issues for the host machine which are undesirable in development. Again I can see why this happens (and that it's needed in production), but is something we should resolve for development.

One fix to a number of these issues would be to add a `Vagrantfile` which points at a suitable base image and have the docker setup run inside that instead. This ensures that we're not placing undue requirements onto developers machines while keeping the setup easy.

**Comment by PeterJCLaw** [comment]
See also #72.

**Comment by sedders123** [comment]
We no longer have an nginx config in this repository
