### ISSUE TITLE
Event pages and event listing

### ISSUE THREAD

**Issue by jimmythompson** [srobo/website#7]
Currently events are stored as a custom Jekyll collection in the `_events` folder.

We should provide, at least, a more complete listing of events on a separate page.

If we could do so without much more effort, we can provide each event a page, with a google map view of the location, and any sort of sign up/ticketing process.

**Comment by PeterJCLaw** [comment]
Note that the previous srweb-jekyll work had a mechanism for generating events from meta-data. It would be good to have that in this version as it:

- makes creating events much easier
- ensures they have a consistent look & feel (including the way the date is spelled)
- enables the creation of a calendar feed with the events in it

**Comment by jimmythompson** [comment]
While the event pages could probably do with some refinement, they work for now.

I'm going to close this. New work around the event pages can be spun into separate issues.
