### ISSUE TITLE
Restore the ordinary homepage

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#78]
Currently the website is in single-page shutdown mode. We need to remove that so we can [announce the competition](https://github.com/srobo/core-team-minutes/issues/29).

**Comment by PeterJCLaw** [comment]
@Adimote I think you've ended up doing this in #81? If so, could you co-ordinate with @RealOrangeOne (as he's assigned to this).

**Comment by Adimote** [comment]
Yes, apologies for jumping in on this, I've actually fixed it in #86 because I split #81 into multiple PRs.
