### ISSUE TITLE
Refresh the brand

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/website#79]
There's a new SR icon and colour, we need to update the pages to pick them up. We should do this at some point, but it's not blocking anything.

@jimmythompson a couple of questions:
- where's the original media for the new icon?
- does the website get the icon directly from the style repo, or does it have its own copy? (I can probably work this one out, but if you happen to know the answer it'd be useful to know)

**Comment by PeterJCLaw** [comment]
@Adimote I think you've ended up doing this in #81? If so, could you co-ordinate with @RealOrangeOne (as he's assigned to this).

**Comment by PeterJCLaw** [comment]
Ok, from what I can tell, #81 covers the icon update but not the colour update. The colour update is dependent on https://github.com/srobo/brand/pull/3.

**Comment by Adimote** [comment]
#85 fixes this, it was previously #81 but I split the PR

**Comment by PeterJCLaw** [comment]
Done as the related PRs have all merged, including https://github.com/srobo/docs/pull/55 which updates the docs.
I pushed changes to update the IDE separately; while it doesn't have the right fonts, it now has the right colours (which is more than it's ever had in the past!)
