### ISSUE TITLE
Choose a licence

### ISSUE THREAD

**Issue by jimmythompson** [srobo/website#9]
We should choose a licence for this repository.

The licence should reflect the values of Student Robotics, and should therefore be GPL-compatible. We also don't want contributors to have to sign agreements.

I'm not sure what caveats might be involved with choosing one particular licence over another, this requires some research.

**Comment by thomasleese** [comment]
We could do something very similar to the [choosealicense.com website](https://github.com/github/choosealicense.com#license) and license the code separate to the content:

> The content of this project itself is licensed under the Creative Commons Attribution 3.0 license, and the underlying source code used to format and display that content is licensed under the MIT license.

My personal preference would be the [MIT License](http://choosealicense.com/licenses/mit/) though because it's well-known, easy for anyone to read and understand, and respects the values of Student Robotics.

**Comment by jimmythompson** [comment]
@rspanton @Adimote @richardbarlow 

Are you happy to include your changes under the MIT license?

**Comment by PeterJCLaw** [comment]
I agree with @thomasleese that it might make sense to license the content separately from the code.

For the record (though as already mentioned in Slack), I'm happy with MIT for my contributions here.

**Comment by Adimote** [comment]
I am happy to include my changes under MIT

**Comment by PeterJCLaw** [comment]
@richardbarlow @rspanton ping on this

**Comment by jimmythompson** [comment]
Regarding licensing the content separately, we've moved content that was previously licensed under MIT from srweb, so applying that to older content would be more difficult.

However, I am happy to license the content I've written under a suitable CC license, and we could apply a suitable rule going forward. I'm not sure where provisions for the press come into things (e.g. fair use) and some parts of CC (like requiring they put the license on their website) feel counter productive.

The alternative is to insist that copyright for content is assigned to Student Robotics on the merging of a pull request.

Thoughts?

**Comment by PeterJCLaw** [comment]
I too don't know how press usage fits into any of this, At our current scale any press coverage is likely to be beneficial and I'm not worried about them using our words (I suspect we'd get a net benefit if they did). Was your concern that the press might be held back from using snippets/content by our license?

I don't feel strongly  about having separate licenses.
The thing which feels like it's affecting us at the moment is the lack of any license at all.

**Comment by richardbarlow** [comment]
I'm happy for all of my changes in this repo to be licensed under MIT.
